### ISSUE TITLE
Text color of some popups left unchanged, so it is barely readable with light theme

### ISSUE THREAD

**Issue by Layerex** [CircuitRCAY/Duvbox#3]
![screen_2020_08_28_21_02_32](https://user-images.githubusercontent.com/59440032/91601606-73a86b80-e959-11ea-8de9-68bb476fa24c.png)
![screen_2020_08_28_21_02_51](https://user-images.githubusercontent.com/59440032/91601610-74d99880-e959-11ea-91c9-706ad48ca2f4.png)
Meanwhile with light theme:
![screen_2020_08_28_21_04_29](https://user-images.githubusercontent.com/59440032/91601612-75722f00-e959-11ea-84d7-1d4f8f3118fa.png)
![screen_2020_08_28_21_04_36](https://user-images.githubusercontent.com/59440032/91601613-760ac580-e959-11ea-8b70-0548dcf80d63.png)

**Comment by CircuitRCAY** [comment]
this will be fixed in the next release, along with a fix for Powercord.
