### ISSUE TITLE
Toasts and color of text in messageboxes left unchanged

### ISSUE THREAD

**Issue by Layerex** [CircuitRCAY/Duvbox#4]
![screen_2020_09_24_17_47_34](https://user-images.githubusercontent.com/59440032/94183640-41275b00-fe92-11ea-9d8b-aeedafa3f32a.png)

![screen_2020_09_24_21_18_37](https://user-images.githubusercontent.com/59440032/94183890-a8450f80-fe92-11ea-816f-b2bb1f049a4d.png)

**Comment by CircuitRCAY** [comment]
What client mod are you using by any chance?

**Comment by Layerex** [comment]
> What client mod are you using by any chance?

BetterDiscord

**Comment by CircuitRCAY** [comment]
Since I do not have a spare client to use BetterDiscord with, I need someone to make a PR to properly support BetterDiscord.

~~For the longest time, it didn't even support Powercord properly.~~

**Comment by Layerex** [comment]
#5. I will probably fix toasts, which are actually BetterDiscord-specific, later.

**Comment by CircuitRCAY** [comment]
Merged.
